project:
  type: website

website:
  title: "001"
  navbar:
    left:
      - href: index.qmd
        text: home
      - about.qmd
      - raw.qmd
      - samling.qmd

format:
  html:
    theme:
      - litera
      - brand
    #mainfont: Courier
    monofont: Menlo
    #font: Courier
    css: styles.css
    toc: true

editor: source
#output-dir: ../_docs
